name: QuadRenderer
channels:
  - defaults
dependencies:
  - numpy=1.19.2
  - pillow=8.0.1
  - pip=20.3.3
  - python=3.6.12
  - plac=1.3.1
  - pip:
    - glfw==2.0.0
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - opencv-python==4.5.1.48

